
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
  - name: plaintext
    port: 29092
    targetPort: 29092
  - name: controller
    port: 29093
    targetPort: 29093
  - name: plaintext-host
    port: 9092
    targetPort: 9092
  - name: jmx
    port: 9101
    targetPort: 9101

---

apiVersion: v1
kind: Service
metadata:
  name: connect
spec:
  selector:
    app: connect
  ports:
  - port: 8083
    targetPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  type: NodePort
  selector:
    app: control-center
  ports:
  - port: 9021
    targetPort: 9021
    nodePort: 31000


---

apiVersion: v1
kind: Service
metadata:
  name: ksqldb-server
spec:
  selector:
    app: ksqldb-server
  ports:
  - port: 8088
    targetPort: 8088

---

apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
spec:
  selector:
    app: rest-proxy
  ports:
  - port: 8082
    targetPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
  - port: 8081
    targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181