apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-master.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    appendonly yes
    cluster-enabled no

  redis-slave.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    appendonly yes
    cluster-enabled no
    replicaof redis-master 6379