apiVersion: v1
kind: Namespace
metadata:
  name: redis-server
  labels:
    app: redis
    environment: staging
    tier: database

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis-server
  labels:
    app: redis
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: redis-server
  labels:
    app: redis
    tier: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        tier: database
    spec:
      nodeSelector:
        node-type: worker
      securityContext:
        fsGroup: 1000
      containers:
      - name: redis-server
        image: redis:7.0-alpine
        args: 
          - "--appendonly"
          - "yes"
          - "--save"
          - "60 1"
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: redis-storage
            mountPath: /data
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: redis-server
  labels:
    app: redis
    tier: database
spec:
  selector:
    app: redis-server
  type: LoadBalancer
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  sessionAffinity: ClientIP