apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: connect
        image: cnfldemos/cp-server-connect-datagen:0.6.4-7.6.0
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: connect-config
---

apiVersion: v1
kind: Service
metadata:
  name: connect
spec:
  selector:
    app: connect
  ports:
  - port: 8083
    targetPort: 8083