apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:latest
        ports:
        - containerPort: 9021
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: control-center-config

---

apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  type: NodePort
  selector:
    app: control-center
  ports:
  - port: 9021
    targetPort: 9021
    nodePort: 31000