# ksqldb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb-server
  template:
    metadata:
      labels:
        app: ksqldb-server
    spec:
      containers:
      - name: ksqldb-server
        image: confluentinc/cp-ksqldb-server:latest.arm64
        ports:
        - containerPort: 8088
        resources:
          requests:
             memory: "64Mi"
             cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: ksqldb-config
        volumeMounts:
        - name: ksqldb-storage
          mountPath: /var/lib/ksqldb
      volumes:
      - name: ksqldb-storage
        persistentVolumeClaim:
          claimName: ksqldb-pvc