apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-proxy
  template:
    metadata:
      labels:
        app: rest-proxy
    spec:
      containers:
      - name: rest-proxy
        image: confluentinc/cp-kafka-rest:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: rest-proxy-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
spec:
  selector:
    app: rest-proxy
  ports:
  - port: 8082
    targetPort: 8082